Check the build result in the GitHub Action

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,3 +29,19 @@ jobs:
           sudo apt-get install -y build-essential libncurses-dev rsync bc \
             cpio python3 unzip wget git file
           ./build.sh
+
+      - name: Check Build
+        run: |
+          FILES="
+          buildroot-2026.02/output/images/rootfs.romfs
+          buildroot-2026.02/output/images/xipImage
+          buildroot-2026.02/output/target/lib/ld-uClibc-1.0.56.so
+          buildroot-2026.02/output/target/lib/libuClibc-1.0.56.so
+          "
+
+          for FILE in $FILES; do
+            if [ ! -f "$FILE" ]; then
+              echo "❌ $FILE is missing!"
+              exit 1
+            fi
+          done
